"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.textStrokeStyle = exports.letterSpacingStyle = exports.placementStyle = exports.fontSizeStyle = exports.fontFamilyStyle = exports.fontColorStyle = exports.sizeStyle = exports.roundStyle = exports.positionStyle = exports.paddingStyle = exports.opacityStyle = exports.marginStyle = exports.colorStyle = exports.borderStyle = exports.blurStyle = exports.imageViewStyle = exports.imageSizeStyle = exports.imagePositionStyle = exports.flexItemsStyle = exports.flexContainerStyle = exports.flexBasicStyle = void 0;
var flex_1 = require("./flex");
Object.defineProperty(exports, "flexBasicStyle", { enumerable: true, get: function () { return flex_1.flexBasicStyle; } });
Object.defineProperty(exports, "flexContainerStyle", { enumerable: true, get: function () { return flex_1.flexContainerStyle; } });
Object.defineProperty(exports, "flexItemsStyle", { enumerable: true, get: function () { return flex_1.flexItemsStyle; } });
var image_1 = require("./image");
Object.defineProperty(exports, "imagePositionStyle", { enumerable: true, get: function () { return image_1.imagePositionStyle; } });
Object.defineProperty(exports, "imageSizeStyle", { enumerable: true, get: function () { return image_1.imageSizeStyle; } });
Object.defineProperty(exports, "imageViewStyle", { enumerable: true, get: function () { return image_1.imageViewStyle; } });
var object_1 = require("./object");
Object.defineProperty(exports, "blurStyle", { enumerable: true, get: function () { return object_1.blurStyle; } });
Object.defineProperty(exports, "borderStyle", { enumerable: true, get: function () { return object_1.borderStyle; } });
Object.defineProperty(exports, "colorStyle", { enumerable: true, get: function () { return object_1.colorStyle; } });
Object.defineProperty(exports, "marginStyle", { enumerable: true, get: function () { return object_1.marginStyle; } });
Object.defineProperty(exports, "opacityStyle", { enumerable: true, get: function () { return object_1.opacityStyle; } });
var object_2 = require("./object");
Object.defineProperty(exports, "paddingStyle", { enumerable: true, get: function () { return object_2.paddingStyle; } });
Object.defineProperty(exports, "positionStyle", { enumerable: true, get: function () { return object_2.positionStyle; } });
Object.defineProperty(exports, "roundStyle", { enumerable: true, get: function () { return object_2.roundStyle; } });
Object.defineProperty(exports, "sizeStyle", { enumerable: true, get: function () { return object_2.sizeStyle; } });
var text_1 = require("./text");
Object.defineProperty(exports, "fontColorStyle", { enumerable: true, get: function () { return text_1.fontColorStyle; } });
Object.defineProperty(exports, "fontFamilyStyle", { enumerable: true, get: function () { return text_1.fontFamilyStyle; } });
Object.defineProperty(exports, "fontSizeStyle", { enumerable: true, get: function () { return text_1.fontSizeStyle; } });
var text_2 = require("./text");
Object.defineProperty(exports, "placementStyle", { enumerable: true, get: function () { return text_2.placementStyle; } });
Object.defineProperty(exports, "letterSpacingStyle", { enumerable: true, get: function () { return text_2.letterSpacingStyle; } });
Object.defineProperty(exports, "textStrokeStyle", { enumerable: true, get: function () { return text_2.textStrokeStyle; } });
