name: automatic release
on:
  push:
    branches:
      - main
    tags:
      - "!*"
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.7.0'

      - name: Install dependencies
        run: yarn install

      - name: Install can-npm-publish and dependencies
        run: |
          npm install can-npm-publish
          npm ci

      - name: Check version and add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./release.sh
#      - name: test
#        run: npm run test
      - name: Build
        run: yarn build

      - name: Release NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
