name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'

      - name: Install Dependencies
        run: yarn install
        run: yarn build:clean

      - name: Run test
        run: yarn test
