"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.textStrokeStyle = exports.letterSpacingStyle = exports.placementStyle = exports.fontSizeStyle = exports.fontFamilyStyle = exports.fontColorStyle = void 0;
var fontColorStyle_1 = require("./fontColorStyle");
Object.defineProperty(exports, "fontColorStyle", { enumerable: true, get: function () { return fontColorStyle_1.fontColorStyle; } });
var fontFamilyStyle_1 = require("./fontFamilyStyle");
Object.defineProperty(exports, "fontFamilyStyle", { enumerable: true, get: function () { return fontFamilyStyle_1.fontFamilyStyle; } });
var fontSizeStyle_1 = require("./fontSizeStyle");
Object.defineProperty(exports, "fontSizeStyle", { enumerable: true, get: function () { return fontSizeStyle_1.fontSizeStyle; } });
var placementStyle_1 = require("./placementStyle");
Object.defineProperty(exports, "placementStyle", { enumerable: true, get: function () { return placementStyle_1.placementStyle; } });
var letterSpacingStyle_1 = require("./letterSpacingStyle");
Object.defineProperty(exports, "letterSpacingStyle", { enumerable: true, get: function () { return letterSpacingStyle_1.letterSpacingStyle; } });
var textStrokeStyle_1 = require("./textStrokeStyle");
Object.defineProperty(exports, "textStrokeStyle", { enumerable: true, get: function () { return textStrokeStyle_1.textStrokeStyle; } });
